# D:/project/blinky/Makefile
# Chỉ định project name, MCU, và source files

PROJECT_NAME := blinky
MCU          := stm8s003f3
PROBE        := stlinkv2
SRC          := blinky.c

# Chỉ định files từ lib cần compile (nếu không dùng thì để trống)
# Ví dụ: stm8s_gpio.c stm8s_clk.c stm8s_tim4.c
LIB_SRC_FILES := stm8s_gpio.c stm8s_clk.c stm8s_tim4.c

include ../../common/Makefile.common